
namespace SV.UPnPLite.Protocols.DLNA
{

    /// <summary>
    ///     Defines an errors that could be generated by a MediaRenderer.
    /// </summary>
    public enum MediaRendererError
    {
        /// <summary>
        ///     An enexpected error occurred on MediaRenderer. Ussually it means that MediaRenderer returned an error which is not defined in UPnP/DLNA protocol.
        /// </summary>
        UnexpectedError = 0,

        /// <summary>
        ///     The immediate transition from current transport state to desired transport state is not supported by this device.
        /// </summary>
        TransitionNotAvailable = 701,

        /// <summary>
        ///     The media does not contain any contents that can be played. 
        /// </summary>
        NoContent = 702,

        /// <summary>
        ///     The media cannot be read (e.g., because of dust or a scratch).
        /// </summary>
        ReadError = 703,

        /// <summary>
        ///     The storage format of the currently loaded media is not supported for playback by this device.
        /// </summary>
        FormatIsNotSupportedForPlayback = 704,

        /// <summary>
        ///     The transport is “hold locked”. (Some portable mobile devices have a small mechanical toggle switch called a “hold lock switch”. While this switch is ON, i.e., the transport is hold 
        ///     locked, the device is guarded against operations such as accidental power on when not in use, or interruption of play or record from accidental pressing of a front panel button or a GUI 
        ///     button.
        /// </summary>
        TransportIsLocked = 705,

        /// <summary>
        ///     The media cannot be written (e.g., because of dust or a scratch).
        /// </summary>
        WriteError = 706,

        /// <summary>
        ///     The media is write-protected or is of a not writable type.
        /// </summary>
        MediaIsProtectedOrNotWritable = 707,

        /// <summary>
        ///     The storage format of the currently loaded media is not supported for recording by this device. 
        /// </summary>
        FormatIsNotSupportedForRecording = 708,

        /// <summary>
        ///     There is no free space left on the loaded media.
        /// </summary>
        MediaIsFull = 709,

        /// <summary>
        ///     The specified seek mode is not supported by the device.
        /// </summary>
        SeekModeNotSupported = 710,

        /// <summary>
        ///     The specified seek target is not specified in terms of the seek mode, or is not present on the media. 
        /// </summary>
        IllegalSeekTarget = 711,

        /// <summary>
        ///     The specified play mode is not supported by the device.
        /// </summary>
        PlayModeNotSupported = 712,

        /// <summary>
        ///     The specified record quality is not supported by the device.
        /// </summary>
        RecordQualityNotSupported = 713,

        /// <summary>
        ///     The specified resource has a MIME-type which is not supported by the AVTransport service.
        /// </summary>
        IllegalMIMEType = 714,

        /// <summary>
        ///      The resource is already being played by other.
        /// </summary>
        ContentIsBusy = 715,

        /// <summary>
        ///      The specified resource cannot be found in the network.
        /// </summary>
        ResourceNotFound = 716,

        /// <summary>
        ///     The specified playback speed is not supported by the AVTransport service.
        /// </summary>
        PlaySpeedIsNotSupported = 717,

        /// <summary>
        ///     The specified instanceID is invalid for this AVTransport.
        /// </summary>
        InvalidInstanceId = 718,

        /// <summary>
        ///     The DNS Server is not available (HTTP error 503).
        /// </summary>
        NoDNSServer = 737,

        /// <summary>
        ///     Unable to resolve the Fully Qualified Domain Name. (HTTP error 502).
        /// </summary>
        BadDomainName = 738,

        /// <summary>
        ///     The server that hosts the resource is unreachable or unresponsive (HTTP error 404/410).  
        /// </summary>
        ServerError = 739
    }
}
